import './style.css';
//import './creationFunctions/of.ts';
//import './creationFunctions/from.ts';
//import './creationFunctions/fromEvent.ts';
//import './creationFunctions/intervals.ts';
//import './creationFunctions/timer.ts';
//import './creationFunctions/forkJoin.ts';
//import './creationFunctions/httpDive.ts';
import './creationFunctions/combineLatest.ts';
